version: "3"
services:
  db:
    image: mysql
    volumes:
      - ${PATH_MYSQL}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
    container_name: ${CONTAINER_NAME_DB}
    restart: always
  web:
    image: ${REPOSITORY}
    links:
      - "db:mysql"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${PATH_HTML}:/var/www/html
      - ${PATH_LOGS}:/var/log
    environment:
      XDEBUG_CONFIG: remote_host={{YOUR_IP_ADDRESS}} # Get you local IP address: ifconfig
    container_name: ${CONTAINER_NAME_WEB}
    restart: always