version: "3.5"
services:
  db:
    image: mysql
    volumes:
      - db-data:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
    restart: always

  web:
    image: alexanderweigelt/devbox
    depends_on:
      - db
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./htdocs:/var/www/html:delegated
      - ./data/logs:/var/log:delegated
    restart: always

volumes:
  db-data:

networks:
  default:
    driver: bridge
