version: "3"
services:
  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  web:
    image: alexanderweigelt/devbox
    links:
      - db:mysql
    ports:
      - 80:80
      - 443:443