version: "3"
services:
  db:
    image: mysql:${MYSQL_VERSION}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - overlay
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
    ports:
      - "3306:3306"
    restart: always
  web:
    depends_on:
      - db
    image: ${REPOSITORY}:${TAG}
    networks:
      - overlay
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./htdocs:/var/www/html:delegated
      - ./data/logs:/var/log:delegated
    restart: always

volumes:
  db-data:

networks:
  overlay:
